### ISSUE TITLE
Best way to generate Vega-Lite spec between source (s) and destination (d)?

### ISSUE THREAD

**Issue by andrewhead** [uwdata/graphscape#16]
Hey graphscape team!  Thanks for sharing this cool tool :)

Given a source viz `s` and destination viz `d`, I want to generate Vega-Lite specs for all viz's `s' ∈ S'` that are exactly one modification towards `d` (the modification can be to marks, data transformations, or encoding).  How would you recommend that I do this?

From the CHI '17 paper ("Design Alternatives" section) it seems like code for this might exist in some form, though I can't find a utility like this in the code base.  The `neighbors` function in `src/transition/neighbor.js` looks relevant: it makes Vega-Lite specs for a set of modifications, though only for encoding changes, and it's not yet clear to me whether the neighbors are all transformations in the direction of destination spec `d`.

Is functionality like this in graphscape?  Or do you have any pointers as to how I might be able to whip up something like this from the existing `sequence` or `transition` methods?

**Comment by yhoonkim** [comment]
Hi @andrewhead !
So Sorry for my late response. I think I missed the notification of this repo...

1.  To get all intermediate specs (`s'`), I'd like to recommend to enumerate them from the source (`s`) by using the edit operations from `transition(s,d)`. But unfortunately, GraphScape doesn't have a function that apply an edit operation to modify a spec now. You might have to figure out this part. Assuming we have this function(let's say `apply`), all possible intermediate specs can be calculated by applying `apply` function `2^n` times, where `n` is the number of the edit operations.

2. Current version of GraphScape repo supports only the two features (`transition`, `sequence`). The applications (which we mentioned in the paper) are not implemented. `neighbor` function do some similar things but doesn't not return what exactly you want. It will only return the fraction of all possible neighbors with given inputs. 

3. You might need to implement a new function as I described in 1. Some of codes in `neighbor` function might be able to be reused but it might be difficult. (My bad...)

Thanks and sorry for this super late response. Please let us know if you need extra help or have thought. (Also, I'd like to hear what you are working on with GraphScape. )

**Comment by andrewhead** [comment]
Thanks @yhoonkim!
